general:
  scale: 3
  m_blocks: 2
  r_blocks: 1
  downsampling: conv
  activation: lrelu
  train_image_path: /path/to/train/images
  val_image_path: /path/to/val/images
  test_image_path: /path/to/test/images
  resize_mode: bicubic
  antialias: True
  image_color_channels: 3
  padding_mode: reflect
  training_crop_size: 256
  validation_crop_size: 480
  test_crop_size: 0
  batch_size: 32
  num_epochs: 100
  optimizer: adam
  learning_rate: 0.0001
  num_workers: 4
  seed: 42
  model_save_path: /path/to/save/model
  model_load_path: /path/to/load/model
  log_path: /path/to/save/log
  log_iters: 10
  device: cuda
  

pretraining:
  enabled: True
  num_channels: 34


prunning:
  enabled: True
  num_channels: 32


bias_removal:
  enabled: True