general:
  scale: 3
  m_blocks: 2
  r_blocks: 1
  downsampling: conv
  activation: lrelu
  train_image_path: ./datasets/train_b
  val_image_path: ./datasets/valid_b
  test_image_path: ./datasets/valid_b
  resize_mode: bicubic
  antialias: True
  image_color_channels: 3
  padding_mode: zeros
  training_crop_size: 324
  validation_crop_size: 480
  test_crop_size: 0
  batch_size: 16
  num_epochs: 120
  optimizer: adam
  learning_rate: 0.0005
  num_workers: 8
  seed: 42
  model_save_path: ./models/stage_all_antialias_true_downsample_bicubic_epoch_1000
  model_load_path: None
  log_path: None
  log_iters: 10
  device: cuda
  

pretraining:
  enabled: True
  num_channels: 34


prunning:
  enabled: True
  num_channels: 32


bias_removal:
  enabled: True